### ISSUE TITLE
Any plans for Arch Linux ?

### ISSUE THREAD

**Issue by ohmyarch** [RoliSoft/WSL-Distribution-Switcher#3]
https://www.archlinux.org/

**Comment by RoliSoft** [comment]
Hi,

The installer supports installing Arch Linux, however, the provided global hook script can only process DEB/RPM-based distributions at this time.

I've already started playing around with adding `pacman` support for the script, it should come soon.

**Comment by ohmyarch** [comment]
@RoliSoft :+1:

**Comment by RoliSoft** [comment]
I've added support for Arch Linux in 6b5ba7d. I've tested it against both `base/archlinux` and `pritunl/archlinux`.

**Comment by thebitstick** [comment]
@RoliSoft Which is more stable?

**Comment by RoliSoft** [comment]
@thebitstick `base/archlinux` seems to be the official one, as far as I can tell, however, it's quite old, the `latest` tag is `2015.06.01`.

`pritunl/archlinux` seems to be the second most popular Arch distribution on the hub, and it's receiving frequent updates, but it's from a third party.

I use the `pritunl/archlinux` version, since `base/archlinux` tends to break a bit after a `pacman -Syu`, that's why the installer script has an intricate dance of which packages to install when, at the "system upgrade" stage. However, you can use the `base/archlinux` version as well, since the script does fix the stuff that breaks after an upgrade.
