### ISSUE TITLE
goreliu's fakefakeroot hack

### ISSUE THREAD

**Issue by fpqc** [RoliSoft/WSL-Distribution-Switcher#4]
Hiya, @RoliSoft I noticed you pushed an update today to support Arch, and I saw that you added @goreliu 's hack to get chroot working.  

He also wrote a little hack to get fakeroot (needed for makepkg) working, where he replaces the fakeroot executable with a shellscript that quits.  Would you add that too?

Also, I like how you stored the binary of the fake libchroot as text, that was a cute trick.

Also, side note, Arch also uses the `wheel` group for sudoer by default.

**Comment by RoliSoft** [comment]
Hi,

I'm investigating alternatives, since his hack will not store the files as root in the archive, which might break some applications further down the line.

AUR has `fakeroot-tcp`, which seems to work, since the only issue with `fakeroot` was the lack of IPC, as far as I can tell:

```
$ yaourt -Sb fakeroot-tcp
$ sudo LD_PRELOAD=/root/libmockchroot.so pacman -U /tmp/yaourt-tmp-RoliSoft/fakeroot-tcp-1.20.2-1-x86_64.pkg.tar.xz
$ whoami
RoliSoft
$ fakeroot whoami
root
```

There's also `fakeroot-ng`, which isn't in AUR, but exists as a rewrite of `fakeroot`. I'll have to test that one as well.

I'll try to update the hook script to setup a working `yaourt` as well, with the proper `fakeroot-tcp` out-of-the-box.

Sidenote: I know, but the `%wheel` line is commented out in Arch's `sudoers`. I've added code in the previous commit to uncomment it.

**Comment by SRGOM** [comment]
@RoliSoft Would you be willing to setup another aur helper (and not yaourt)? As shown [here](https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table), yaourt is the least green, pacaur, aurutils, bauerbill being the most. I specifically don't like that yaourt by default doesn't even give the option of reading PKGBUILD file.

**Comment by cclements** [comment]
+1 for pacaur

**Comment by RoliSoft** [comment]
ba7d799 automatically installs the working `fakeroot-tcp`.

It doesn't install an AUR helper at this point, since I'm undecided which one to go with.

I'm also undecided on whether I should create a wrapper for pacman which includes the `LD_PRELOAD`, because right now, you can't directly install with `makepkg -si`, pacman will fail on the `chroot` issue. You'll need to do `makepkg -s` and install the package manually with `LD_PRELOAD=... pacman -U *.pkg.xz`.

**Comment by RoliSoft** [comment]
As of commit aa4457a, `pacaur` is automatically installed on Arch.
