### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by triksywabbit** [RoliSoft/WSL-Distribution-Switcher#47]
Not an issue persay, but I really love your colour scheme in the WSL preview screenshot. Any chance you could post your config?

**Comment by RoliSoft** [comment]
The terminal is using the Monokai color scheme slightly tweaked (different background and some colors [notably yellow] are more vibrant) to my taste.

ConEmu's ConEmu.xml: (Mainly use it for Win32 console, such as CMD and PowerShell)

	<value name="ColorTable00" type="dword" data="00211f1d"/>
	<value name="ColorTable01" type="dword" data="009e5401"/>
	<value name="ColorTable02" type="dword" data="0004aa74"/>
	<value name="ColorTable03" type="dword" data="00a6831a"/>
	<value name="ColorTable04" type="dword" data="003403a7"/>
	<value name="ColorTable05" type="dword" data="009c5689"/>
	<value name="ColorTable06" type="dword" data="0049b6b6"/>
	<value name="ColorTable07" type="dword" data="00cacaca"/>
	<value name="ColorTable08" type="dword" data="007c7c7c"/>
	<value name="ColorTable09" type="dword" data="00ffa255"/>
	<value name="ColorTable10" type="dword" data="0006d08d"/>
	<value name="ColorTable11" type="dword" data="00e5c258"/>
	<value name="ColorTable12" type="dword" data="004b04f3"/>
	<value name="ColorTable13" type="dword" data="00b87da8"/>
	<value name="ColorTable14" type="dword" data="0000d7ff"/>
	<value name="ColorTable15" type="dword" data="00ffffff"/>
	<value name="ColorTable16" type="dword" data="00000000"/>
	<value name="ColorTable17" type="dword" data="00800000"/>
	<value name="ColorTable18" type="dword" data="00008000"/>
	<value name="ColorTable19" type="dword" data="00808000"/>
	<value name="ColorTable20" type="dword" data="00000080"/>
	<value name="ColorTable21" type="dword" data="00800080"/>
	<value name="ColorTable22" type="dword" data="00008080"/>
	<value name="ColorTable23" type="dword" data="00c0c0c0"/>
	<value name="ColorTable24" type="dword" data="00808080"/>
	<value name="ColorTable25" type="dword" data="00ff0000"/>
	<value name="ColorTable26" type="dword" data="0000ff00"/>
	<value name="ColorTable27" type="dword" data="00ffff00"/>
	<value name="ColorTable28" type="dword" data="000000ff"/>
	<value name="ColorTable29" type="dword" data="00ff00ff"/>
	<value name="ColorTable30" type="dword" data="0000ffff"/>
	<value name="ColorTable31" type="dword" data="00ffffff"/>

MinTTY's .minttyrc: (Mainly use it for ANSI terminals until CMD gets better, for Cygwin and WSL, through [WSLTTY](https://github.com/mintty/wsltty))

	BackgroundColour=29,31,33
	ForegroundColour=255,255,255
	CursorColour=255,255,255
	Black=29,31,33
	BoldBlack=124,124,124
	Red=167,3,52
	BoldRed=243,4,75
	Green=116,170,4
	BoldGreen=141,208,6
	Yellow=182,182,73
	BoldYellow=255,215,0
	Blue=1,84,158
	BoldBlue=85,162,255
	Magenta=137,86,156
	BoldMagenta=168,125,184
	Cyan=26,131,166
	BoldCyan=88,194,229
	White=202,202,202
	BoldWhite=255,255,255

While I like ConEmu, WSL doesn't work really great under it due to the [differences described here](https://conemu.github.io/en/CygwinAnsi.html). Most notably mouse support is lacking, especially if you like using tmux/vim with the mouse as well.
