### ISSUE TITLE
Clean Arch Install, latest pull

### ISSUE THREAD

**Issue by fpqc** [RoliSoft/WSL-Distribution-Switcher#6]
Heya, @RoliSoft 

I have a log of a brand new install off a new arch.SFS and you mislocated the libmockchroot in the preinstall script, probably forgot to change its location later on.

Also, lots of problems with sigchecks failing even after fixing that on my end.  It says it can't look up the keys remotely.

Edit: Oops, I pulled it like 4 hours ago =.=.

Edit2: Nope, I was right, you are overwriting it after all.  Find where you write "libfakechroot" and you'll see you're overwriting it.

Anyway, after fixing it, I think you need to add two lines to the postinstall script for arch:
`pacman-key --init`

`pacman-key --populate archlinux`

Edit: Maybe I'll just do a pull request

Anyway, afterwards, I'm still getting this acl error afterwards

Edit 3: I'm going to fix this properly then submit a proper pull request.  The last one was messed up.

**Comment by fpqc** [comment]
Problem was just populating pacman-key, not any of the other stuff.

Edit: Nah, now it's just broken =\

**Comment by RoliSoft** [comment]
Hi,

Keep in mind the SquashFS version from the ISO requires you to go through the whole installation procedure, as described in the [installation guide](https://wiki.archlinux.org/index.php/installation_guide#Installation).

Since one of the steps is selecting the mirror for pacman, that is why you are unable to do anything with it.

I recommend using `get-prebuilt.py` with the newer 3rd-party `pritunl/archlinux`, or the older official `base/archlinux`. Both are fully supported, but the 3rd-party version will setup faster, since it requires less updating and tweaking.

You can, of course, use the SquashFS version, but then please follow the official installation guide to complete it.

I'm not sure if there is much benefit to using the SquashFS versions, but I'll check it out later tonight, and update the hook script _if_ it does not require much tweaking.

> Problem was just populating pacman-key, not any of the other stuff.

For the docker versions, `pacman -S archlinux-keyring` populates the database with the new keys, but in your case, I presume you haven't selected a mirror yet, and as such cannot install packages.

> you mislocated the libmockchroot in the preinstall script,

I haven't, there's a `pacman -S fakechroot` which installs a better library for purpose and I switch the primitive chroot mocker to that library, but I presume you noticed this and that's why you closed the pull request.

> Anyway, afterwards, I'm still getting this acl error afterwards

Are you talking about `dlsym(acl_get_fd): ...: undefined symbol: acl_get_fd` during `makepkg`/`pacaur`?

Those aren't errors, just warnings issued by `fakeroot-tcp`, since WSL doesn't have those functions defined, so it can't mock them.

**Comment by fpqc** [comment]
Thanks!

**Comment by RoliSoft** [comment]
Released new hook in 978ec74, which builds new `fakeroot` from ABS after patching, instead of the older `fakeroot-tcp` version from AUR, last updated around 2012.

This version isn't spamming the console with `undefined symbol` warnings.
