### ISSUE TITLE
CentOS can't start services (eg. SSH)

### ISSUE THREAD

**Issue by DeadPixelz01** [RoliSoft/WSL-Distribution-Switcher#60]
When I try to start something like SSH, I get the following error:
`Failed to get D-Bus connection: Operation not permitted`

On the CentOS docker page, they mention that you need to use this [pre-build](https://hub.docker.com/r/centos/systemd/) and then lunch it using:
`docker run --privileged --name httpd -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 -d  httpd`

I can download the pre-build just fine, but how would you implement the docker run command from above?

**Comment by RoliSoft** [comment]
WSL doesn't support services at this time, as far as I know. This is something to discuss in the WSL issue tracker. See: https://github.com/Microsoft/BashOnWindows/issues/376

**Comment by DeadPixelz01** [comment]
But if I run 'sudo service ssh --full-restart' I get the following:
```
 * Stopping OpenBSD Secure Shell server sshd                                           [ OK ]
 * Starting OpenBSD Secure Shell server sshd   
```
And then if I open up something like PuTTY and connect to '127.0.0.1', I'm in :P

EDIT: This is on the version of Ubuntu that comes with WSL

**Comment by RoliSoft** [comment]
Processes can run in the background while your WSL console is open, but will be closed when you close it. At least, that's what happened last time I checked.

In your case the issue is with D-Bus, so try fixing that. As far as I know, it's fixable, but has the same issue of closing once you close the console. Check out the tutorials which install a full desktop environment, since that requires D-Bus too.
