### ISSUE TITLE
centos7 - systemctl not work, any command - return "Failed to get D-Bus connection: Operation not permitted"

### ISSUE THREAD

**Issue by xukku** [RoliSoft/WSL-Distribution-Switcher#72]
any command like

systemctl list-units  
systemctl 
systemctl start firewalld.service
...

**Comment by WSLUser** [comment]
"Failed to get D-Bus connection: Operation not permitted" services don't automatically start as of yet in WSL thanks to `init` being emulated. Do `sudo service dbus start `to start dbus. As far as `systemctl `goes, it's not supported but there's a GitHub issue open for it search for it under Microsoft/WSL. This repo on GitHub isn't the authoritative source for WSL. The one I listed is. All @RoliSoft is responsible for is his little project he created here to enable different distros to be run using his distribution-switcher. Which at this point shouldn't even exist now since all it takes is a distro vendor speaking to Microsoft to get their distro on the Windows Store.

**Comment by xukku** [comment]
i tried this
`sudo service dbus start`

and got that 

```
Redirecting to /bin/systemctl start dbus.service
Failed to get D-Bus connection: Operation not permitted
```
```

# cat /etc/*-release
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)
```

**Comment by WSLUser** [comment]
Try in natively installed Ubuntu. If this continues see https://github.com/Microsoft/WSL and read contribute instructions to file a issue with them. Also file a issue with CentOS to distribute their distro to the Windows Store. Most likely you'll experience a few less issues than using the distribution-switcher. Though as I said, `systemctl` isn't supported yet. There is no real `systemd` to speak of and that is part of why `systemctl` doesn't work by default.  Basically any syscalls that depend on it will fail at some point. The question is if it it'll be a hard fail or a soft fail and can it work despite it. Most likely the answer to that will be no.
Edit: I did have a insight just now that performing a `chown` or `chmod` may stop the "Operation not permitted" message as it's usually a permission issue.  If it doesn't work, still do the above.

**Comment by BetsuNo** [comment]
I've solve the problem with a daemons management by adding a good old rc.d scripts for a daemons I use.

**Comment by WSLUser** [comment]
we can get CentOS in a more official manner now from Wlinux Enterprise (just convert from Scientific Linux to CentOS). Could you post steps and a gist of your scripts?

**Comment by BetsuNo** [comment]
I use only nginx, php-fpm and memcached daemons. Here is my scripts https://gist.github.com/BetsuNo/331f6ecc3b0bc5b3997bf2098235ae2e
Place them into ```/etc/rc.d/init.d``` dir. Then you can manage a daemons with ```service``` command. Like ```service nginx restart``` or ```service php-fpm restart```
